language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

branches:
  only:
  - master
  - develop
  - /^release\/.*$/

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8